### ISSUE TITLE
Request updates to roles-and-teams.md file.

### ISSUE THREAD

**Issue by JimmySunDance** [UKHomeOffice/cop-design-guidelines#10]
Please update the section regarding the role of the "Candidate Users" section. 
Current:

> On the ‘Process properties’ panel in the ‘General’ tab it is necessary to fill in the ‘Candidate Starter Groups’ box with the correct role/roles (it could be a comma separated string) e.g. ‘copge’(COP general user). This role is configured in Keycloak SSO. Please consult your technical architect and/or your user researcher for the correct role definition for your particular use case.

Suggested:

> On the 'Process properties' panel in the 'General' tab it is necessary to fill in the 'Candidate Starter Groups' box with the correct role/roles (it could be a comma separated string) e.g. 'copge'(COP general user). This role is configured in Keycloak SSO. **If this field is left blank, all users are able to view the task**. Please consult your technical architect and/or your user researcher for the correct role definition for your particular use case.

**Comment by aminmc** [comment]
Roles does not apply to tasks. Roles at the process level is related to case view and whether you can see a process instance in the case. It is not related to tasks. Tasks are bound by team code.

**Comment by aminmc** [comment]
The current documentation clearly says what purpose roles serves and what team code. Role **DOES NOT** apply to tasks. Team codes apply to tasks.
